### ISSUE TITLE
sc-test-suite.lsp

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken-RTs#1] opened 2019-02-26 09:57 UTC
ll. 140458 - 60

Relative file paths in test suite, think they're breaking the tests for me.

**Comment by danieljamesross** [comment] 2019-02-26 10:01
I've deleted all .fasl files and reinstalled sc and clm-5.

These are the fails I get.

    Testing: (TEST-SNDFILE-PALETTE-MAKE-SFP-FROM-FOLDER)...
    
    FAIL: (TEST-SNDFILE-PALETTE-MAKE-SFP-FROM-FOLDER): 
    (WHEN (PROBE-FILE /music/hyperboles/snd/cello/samples/11/)
      (SETQ SFP1
              (MAKE-SFP-FROM-FOLDER /music/hyperboles/snd/cello/samples/11/
                                    AUTO-FREQ
                                    #'(LAMBDA (PATH)
                                        (LET* ((PNN (PATHNAME-NAME PATH))
                                               (DASH-POS (POSITION - PNN))
                                               (NOTE (SUBSEQ PNN 0 DASH-POS)))
                                          (FREQUENCY (MAKE-PITCH NOTE)))))))    
    
    FAIL: (TEST-SNDFILE-PALETTE-MAKE-SFP-FROM-FOLDER): 
    (EQUAL-WITHIN-TOLERANCE (FREQUENCY (FIRST (DATA (FIRST (DATA SFP1)))))
                            554.36523)
    
    Testing: (TEST-CLM-PLAY-PSYNCH)...
    WARNING:
       sc-test-suite-aux::file-write-ok: file /tmp/mini-1-vn-vc-sines-to-sines2-seq1-3-psync.wav has size     80 (expected minimum 2000000)
    
    FAIL: (TEST-CLM-PLAY-PSYNCH): 
    (FILE-WRITE-OK /tmp/mini-1-vn-vc-sines-to-sines2-seq1-3-psync.wav 2000000)
    WARNING:
       sc-test-suite-aux::file-write-ok: file /tmp/mini-1-vn-sines-to-sines2-seq1-3-psync.wav has size 80 (expected minimum 2000000)

    FAIL: (TEST-CLM-PLAY-PSYNCH): 
    (FILE-WRITE-OK /tmp/mini-1-vn-sines-to-sines2-seq1-3-psync.wav 2000000)

**Comment by mdedwards** [comment] 2019-02-26 10:09
so there are two issues there:
1) (WHEN (PROBE-FILE /music/hyperboles/snd/cello/samples/11/):
fixed (test should have been within the when)

2) clm-play-psynch
not fixed: passes for me and there are no relative file paths there, right?
looks like there's a problem with your CLM installation. Is it working elsewhere?

**Comment by danieljamesross** [comment] 2019-02-26 10:16
1. cool
2. CLM works fine on my test piece

**Comment by mdedwards** [comment] 2019-02-26 10:23
get latest code then change the name of the directory of where the test-suite files live to 'test-suite'

**Comment by danieljamesross** [comment] 2019-02-26 10:29
Had already changed name to test-suite.

Have downloaded latest. Still failing:

    FAIL: (TEST-SNDFILE-PALETTE-MAKE-SFP-FROM-FOLDER): 
    (WHEN (PROBE-FILE /music/hyperboles/snd/cello/samples/11/)
      (SETQ SFP1
              (MAKE-SFP-FROM-FOLDER /music/hyperboles/snd/cello/samples/11/
                                    AUTO-FREQ
                                    #'(LAMBDA (PATH)
                                        (LET* ((PNN (PATHNAME-NAME PATH))
                                               (DASH-POS (POSITION - PNN))
                                               (NOTE (SUBSEQ PNN 0 DASH-POS)))
                                          (FREQUENCY (MAKE-PITCH NOTE))))))
      (EQUAL-WITHIN-TOLERANCE (FREQUENCY (FIRST (DATA (FIRST (DATA SFP1)))))
                              554.36523))

        Testing: (TEST-CLM-PLAY-PSYNCH)...
    WARNING:
       sc-test-suite-aux::file-write-ok: file /tmp/mini-1-vn-vc-sines-to-sines2-seq1-3-psync.wav has size     80 (expected minimum 2000000)

    FAIL: (TEST-CLM-PLAY-PSYNCH): 
    (FILE-WRITE-OK /tmp/mini-1-vn-vc-sines-to-sines2-seq1-3-psync.wav 2000000)
    WARNING:
       sc-test-suite-aux::file-write-ok: file /tmp/mini-1-vn-sines-to-sines2-seq1-3-psync.wav has size 80     (expected minimum 2000000)

    FAIL: (TEST-CLM-PLAY-PSYNCH): 
    (FILE-WRITE-OK /tmp/mini-1-vn-sines-to-sines2-seq1-3-psync.wav 2000000)

**Comment by mdedwards** [comment] 2019-02-26 10:36
that's not the latest code: you've missed an update on the (when.... try again.

if your dir is called test-suite and clm is working then I can't really help you. You'll have to look at the backtrace. It looks like CLM is just writing the header. This could be caused by it not finding the sound files. make sure sine-250.wav and sine-a4.wav are in test-suite--they're in the repo.

must get back to my score...I've got a deadline this week.

**Comment by mdedwards** [comment] 2019-02-26 18:13
closing: fixed via online chat

**Closed as completed by mdedwards** 2019-02-26 18:13 UTC
